In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/student_performance2000.csv')

In [4]:
dataset.head(5)

id  study_hours  attendance_percent  sleep_hours  previous_score  \
0   1          2.0                60.5          5.5              45   
1   2          2.5                62.0          5.8              48   
2   3          3.0                65.0          6.0              50   
3   4          3.2                66.5          6.2              52   
4   5          3.5                68.0          6.5              54   

   final_score  
0           50  
1           52  
2           55  
3           57  
4           58

In [5]:
x =  dataset.iloc[:,:-1]
y = dataset["final_score"]

In [6]:
new_data = dataset.head(10)

In [7]:
from sklearn.model_selection import LeaveOneOut, LeavePOut, KFold, StratifiedKFold

In [8]:
 lo = LeaveOneOut()
 for train, test in lo.split(x,y):
   print(train, test)

Streaming output truncated to the last 5000 lines.
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890 891 892 893 894 895 896 897 898 899
 900 901 902 903 904 905 906 907 908 909 911 912 913 914 915 916 917 918
 919 920 921 922 923 924 925 926 927 928 929 930 931 932 933 934 935 936
 937 938 939 940 941 942 943 944 945 946 947 948 949 950 951 952 953 954


In [9]:
x_new = new_data.iloc[:,:-1]
y_new = new_data["final_score"]

In [10]:
 lo = LeaveOneOut()
 for train, test in lo.split(x_new, y_new):
   print(train, test)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


In [11]:
 lo = LeavePOut(p=3)
 for train, test in lo.split(x_new, y_new):
   print(train, test)

[3 4 5 6 7 8 9] [0 1 2]
[2 4 5 6 7 8 9] [0 1 3]
[2 3 5 6 7 8 9] [0 1 4]
[2 3 4 6 7 8 9] [0 1 5]
[2 3 4 5 7 8 9] [0 1 6]
[2 3 4 5 6 8 9] [0 1 7]
[2 3 4 5 6 7 9] [0 1 8]
[2 3 4 5 6 7 8] [0 1 9]
[1 4 5 6 7 8 9] [0 2 3]
[1 3 5 6 7 8 9] [0 2 4]
[1 3 4 6 7 8 9] [0 2 5]
[1 3 4 5 7 8 9] [0 2 6]
[1 3 4 5 6 8 9] [0 2 7]
[1 3 4 5 6 7 9] [0 2 8]
[1 3 4 5 6 7 8] [0 2 9]
[1 2 5 6 7 8 9] [0 3 4]
[1 2 4 6 7 8 9] [0 3 5]
[1 2 4 5 7 8 9] [0 3 6]
[1 2 4 5 6 8 9] [0 3 7]
[1 2 4 5 6 7 9] [0 3 8]
[1 2 4 5 6 7 8] [0 3 9]
[1 2 3 6 7 8 9] [0 4 5]
[1 2 3 5 7 8 9] [0 4 6]
[1 2 3 5 6 8 9] [0 4 7]
[1 2 3 5 6 7 9] [0 4 8]
[1 2 3 5 6 7 8] [0 4 9]
[1 2 3 4 7 8 9] [0 5 6]
[1 2 3 4 6 8 9] [0 5 7]
[1 2 3 4 6 7 9] [0 5 8]
[1 2 3 4 6 7 8] [0 5 9]
[1 2 3 4 5 8 9] [0 6 7]
[1 2 3 4 5 7 9] [0 6 8]
[1 2 3 4 5 7 8] [0 6 9]
[1 2 3 4 5 6 9] [0 7 8]
[1 2 3 4 5 6 8] [0 7 9]
[1 2 3 4 5 6 7] [0 8 9]
[0 4 5 6 7 8 9] [1 2 3]
[0 3 5 6 7 8 9] [1 2 4]
[0 3 4 6 7 8 9] [1 2 5]
[0 3 4 5 7 8 9] [1 2 6]
[0 3 4 5 6 8 9] [1 2 7]
[0 3 4 5 6 7 9] 

In [12]:
 lo = KFold(n_splits=5)
 for train, test in lo.split(x_new, y_new):
   print(train, test)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [13]:
#  lo = StratifiedKFold(n_splits=5)
#  for train, test in lo.split(x_new, y_new):
#    print(train, test)

In [14]:
from sklearn.model_selection import cross_val_score

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
p = cross_val_score(LinearRegression(),x,y, cv=5)

In [18]:
p.sort()
p*100

array([-7.31188057, -7.18509943, -4.15353   , -1.49061314,  0.56183515])

In [19]:
p1 = cross_val_score(LinearRegression(),x,y, cv=KFold(n_splits=50))

In [20]:
p1.sort()
p1*100

array([-34.27136611, -31.43053066, -30.74019288, -30.16734956,
       -26.40009924, -25.05087079, -23.50836606, -20.5649112 ,
       -19.58918562, -17.29787469, -16.06406465, -12.94723294,
       -12.27950236, -11.01294253, -10.22897351,  -9.81957931,
        -8.02162348,  -7.86370636,  -6.73509907,  -5.65327652,
        -4.8123143 ,  -4.80808357,  -4.55062725,  -4.51266226,
        -4.18287002,  -3.63622728,  -3.63341049,  -3.16213951,
        -2.29292836,  -1.35456638,  -0.97136365,  -0.87280921,
        -0.65947984,  -0.21272466,   0.11897404,   0.61580172,
         1.39157275,   1.41521459,   1.43841255,   3.0975989 ,
         3.63595072,   3.65609978,   4.05429127,   4.49064113,
         4.67029062,   6.66142193,   9.0722659 ,  11.56130828,
        13.70292025,  35.08161538])